using System;
using System.Collections.Generic;
using DreamCodeVR2.ContextBridge;
using DreamCodeVR2.Quest;
using DreamCodeVR2.SceneContext;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using Ubiq.XR;

namespace DreamCodeVR2.ExperimentalAuthoring
{
    // Development/researcher-only console. It never appears in a participant build unless explicitly enabled.
    public class ExperimentalResearcherPanel : MonoBehaviour
    {
        public bool researcherMode; public KeyCode toggleKey=KeyCode.F5;
        public ExperimentConditionManager conditionManager; public AuthoringProtocolClient protocol; public QuestRuntimeState quest; public InteractionContextProvider interaction; public SceneContextTransmitter sceneContext; public DreamCodeVR2ResearcherControlClient researcherControl;
        public float controllerToggleHoldSeconds=1f; private float controllerToggleStarted=-1f;
        private GameObject panel; private TMP_Text live; private TMP_Text log; private DynamicStoryTaskController dynamicStory; private HandController leftHand; private HandController rightHand; private readonly Queue<string> lines=new Queue<string>();
        private void Start(){Resolve();if(!CanShow())return;Build();panel.SetActive(false);ResearcherUiInteractionState.IsResearcherUiInteractionActive=false;}
        private void OnDestroy(){ResearcherUiInteractionState.IsResearcherUiInteractionActive=false;}
        private void Update(){if(panel&&Input.GetKeyDown(toggleKey))Toggle();UpdateControllerToggle();if(panel&&panel.activeSelf)Refresh();}
        private bool CanShow()=>researcherMode||(conditionManager&&conditionManager.studyConfiguration&&conditionManager.studyConfiguration.researcherMode)||Debug.isDebugBuild;
        private void Resolve(){if(!conditionManager)conditionManager=FindFirstObjectByType<ExperimentConditionManager>();if(!protocol)protocol=FindFirstObjectByType<AuthoringProtocolClient>();if(!quest)quest=FindFirstObjectByType<QuestRuntimeState>();if(!interaction)interaction=FindFirstObjectByType<InteractionContextProvider>();if(!sceneContext)sceneContext=FindFirstObjectByType<SceneContextTransmitter>();if(!dynamicStory)dynamicStory=FindFirstObjectByType<DynamicStoryTaskController>();ResolveHands();if(!researcherControl){researcherControl=GetComponent<DreamCodeVR2ResearcherControlClient>()??gameObject.AddComponent<DreamCodeVR2ResearcherControlClient>();researcherControl.configuration=conditionManager?conditionManager.studyConfiguration:null;}}
        private void Build()
        {
            var canvasObject=new GameObject("ExperimentalResearcherPanel",typeof(RectTransform),typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster),typeof(XRUICanvas));canvasObject.transform.SetParent(transform,false);var canvas=canvasObject.GetComponent<Canvas>();canvas.renderMode=RenderMode.WorldSpace;canvas.worldCamera=Camera.main;canvasObject.transform.localScale=Vector3.one*.0014f;var camera=Camera.main;if(camera){canvasObject.transform.position=camera.transform.position+camera.transform.forward*1.15f-camera.transform.up*.1f;canvasObject.transform.rotation=Quaternion.LookRotation(canvasObject.transform.position-camera.transform.position);}
            panel=CreateBox("Panel",canvasObject.transform,new Color(.035f,.05f,.075f,.97f));var rect=panel.GetComponent<RectTransform>();rect.anchorMin=new Vector2(0,1);rect.anchorMax=new Vector2(0,1);rect.pivot=new Vector2(0,1);rect.anchoredPosition=new Vector2(18,-18);rect.sizeDelta=new Vector2(500,720);var layout=panel.AddComponent<VerticalLayoutGroup>();layout.padding=new RectOffset(14,14,12,12);layout.spacing=6;layout.childControlWidth=true;layout.childControlHeight=false;
            AddText(panel.transform,"DreamCodeVR2 · Researcher Console",20,FontStyles.Bold);AddText(panel.transform,"LOCAL TOOLING — NOT SERVER E2E",12,FontStyles.Italic);
            AddHeader(panel.transform,"SESSION");AddButtons(panel.transform,new (string,Action)[]{("START",StartServerSession),("END",EndServerSession),("RESET RUN",ResetCurrentRun),("REFRESH CONTEXT",()=>sceneContext?.SendSceneContextSnapshot("researcher refresh"))});
            AddHeader(panel.transform,"CONDITION (resets playthrough)");AddButtons(panel.transform,new (string,Action)[]{("C1 VOICE",()=>Switch(ExperimentCondition.VoiceCommandBaseline)),("C2 AUTHOR",()=>Switch(ExperimentCondition.PlayerAuthoring)),("C3 STORY",()=>Switch(ExperimentCondition.DynamicStorytelling))});
            AddHeader(panel.transform,"LIVE STATE");live=AddText(panel.transform,"",12,FontStyles.Normal);live.rectTransform.sizeDelta=new Vector2(0,120);
            AddHeader(panel.transform,"OBJECT SELECTION");AddButtons(panel.transform,new (string,Action)[]{("TABLE DRAWER",()=>Select("table_drawer_001")),("KEY",()=>Select("key_001")),("LOCK",()=>Select("lock_001")),("DOOR",()=>Select("door_001")),("LAMP",()=>Select("lamp_001"))});
            AddHeader(panel.transform,"LOCAL TEST INJECTION");AddButtons(panel.transform,new (string,Action)[]{("C1 OPEN",()=>Predefined("OPEN")),("C1 CLOSE",()=>Predefined("CLOSE")),("C2 GRABBABLE",()=>Affordance("grabbable",true)),("C2 RED",()=>SetDrawerColor()),("ROTATE",()=>Behavior("rotate_continuously",45)),("BLINK",()=>Behavior("blink",.5f)),("C3 NEXT TASK",()=>SimulateNextTask())});
            AddHeader(panel.transform,"LOG");log=AddText(panel.transform,"",11,FontStyles.Normal);log.rectTransform.sizeDelta=new Vector2(0,125);Note("console ready");
        }
        private void Switch(ExperimentCondition condition){conditionManager?.PrepareResearcherCondition(condition);Note("condition selected: "+condition+". Press START.");}
        private void StartServerSession(){var peer=protocol?.CurrentPeerUuid;if(string.IsNullOrEmpty(peer)){Note("NO PEER UUID — wait for Ubiq connection.");return;}researcherControl.Health(health=>{if(!health.healthy||!string.IsNullOrEmpty(health.error)){Note("RESEARCHER API UNREACHABLE");return;}Action<DreamCodeVR2ResearcherControlClient.Response> ready=r=>{if(!string.IsNullOrEmpty(r.error)||string.IsNullOrEmpty(r.session_id)){Note("SESSION START FAILED: "+r.error);return;}conditionManager.ResetPlaythrough();conditionManager.sessionId=r.session_id;conditionManager.StartSession(false);sceneContext?.SendSceneContextSnapshot("session ready");researcherControl.GetStatus(peer,status=>{if(!string.IsNullOrEmpty(status.error)||status.session_id!=conditionManager.sessionId||status.condition!=DreamCodeVR2ResearcherControlClient.ServerCondition(conditionManager.condition)){Note("SESSION STATUS MISMATCH");conditionManager.CompleteSession();return;}Note("SESSION READY: "+conditionManager.sessionId);});};if(conditionManager.sessionStarted)researcherControl.RestartSession(conditionManager.selectedCondition,peer,ready);else researcherControl.StartSession(conditionManager.selectedCondition,peer,ready);});}
        private void EndServerSession(){var peer=protocol?.CurrentPeerUuid;if(string.IsNullOrEmpty(peer))return;researcherControl.EndSession(peer,r=>{if(!string.IsNullOrEmpty(r.error)||!r.ended){Note("SESSION END FAILED: "+r.error);return;}conditionManager?.ResetPlaythrough();Note("NO ACTIVE SESSION");});}
        private void ResetCurrentRun(){var peer=protocol?.CurrentPeerUuid;if(string.IsNullOrEmpty(peer))return;researcherControl.ResetSession(peer,r=>{if(!string.IsNullOrEmpty(r.error)||!r.reset){Note("SERVER RESET FAILED: "+r.error);return;}conditionManager?.ResetPlaythrough();Note("RUN RESET");});}
        private void Toggle(){panel.SetActive(!panel.activeSelf);ResearcherUiInteractionState.IsResearcherUiInteractionActive=panel.activeSelf;if(panel.activeSelf)PositionInFrontOfHead();}
        private void PositionInFrontOfHead(){var camera=Camera.main;if(!camera)return;panel.transform.parent.position=camera.transform.position+camera.transform.forward*1.15f-camera.transform.up*.1f;panel.transform.parent.rotation=Quaternion.LookRotation(panel.transform.parent.position-camera.transform.position);}
        private void ResolveHands(){if(leftHand&&rightHand)return;foreach(var hand in FindObjectsByType<HandController>(FindObjectsSortMode.None)){if(hand.Left)leftHand=hand;if(hand.Right)rightHand=hand;}}
        private void UpdateControllerToggle(){ResolveHands();var left=leftHand&&(leftHand.MenuButtonState||leftHand.PrimaryButtonState);var right=rightHand&&(rightHand.MenuButtonState||rightHand.PrimaryButtonState);if(left&&right){if(controllerToggleStarted<0)controllerToggleStarted=Time.unscaledTime;if(Time.unscaledTime-controllerToggleStarted>=controllerToggleHoldSeconds){Toggle();controllerToggleStarted=float.PositiveInfinity;}}else controllerToggleStarted=-1f;}
        private void Select(string id){var obj=AuthoringActionExecutor.FindEditable(id);var selector=FindFirstObjectByType<global::SelectObjectRay>();if(obj&&selector)selector.selectedObject=obj.gameObject;sceneContext?.SendSceneContextSnapshot("researcher selection");Note(obj?"selected "+id:"object unavailable: "+id);}
        private void Predefined(string command){var r=protocol?.ExecuteLocalPredefined(new PredefinedVoiceCommand{commandId="local-"+Guid.NewGuid(),targetObjectId="table_drawer_001",command=command});Note(command+": "+r?.message);}
        private void Affordance(string operation,bool value){var r=protocol?.ExecuteLocalSceneApi(new SceneApiCall{method="SceneAPI.setAffordance",action=new AuthoringAction{actionId="local-"+Guid.NewGuid(),targetObjectId="table_drawer_001",operation=operation,value=value?"true":"false"}});Note("affordance: "+r?.message);}
        private void SetDrawerColor(){var r=protocol?.ExecuteLocalSceneApi(new SceneApiCall{method="SceneAPI.setProperty",action=new AuthoringAction{actionId="local-"+Guid.NewGuid(),targetObjectId="table_drawer_001",operation="color",value="#B83232"}});Note("color: "+r?.message);}
        private void Behavior(string operation,float value){var r=protocol?.ExecuteLocalBehaviorApi(new BehaviorApiCall{method="BehaviorAPI.addBehavior",action=new AuthoringAction{actionId="local-"+Guid.NewGuid(),targetObjectId="table_drawer_001",operation=operation,numericValue=value}});Note("behavior: "+r?.message);}
        private void SimulateNextTask(){if(!dynamicStory){Note("dynamic controller unavailable");return;}var ok=dynamicStory.ActivateNextTask(new NextTaskSpec{taskId="local-next",playerInstruction="Pick up the key.",requiredObjects=new[]{"key_001"},successConditions=new[]{new RuntimeSuccessCondition{type="OBJECT_GRABBED",object_id="key_001"}}},out var error);Note(ok?"next task activated":"next task rejected: "+error);}
        private void Refresh(){var selected=interaction?.GetCurrentSelectedEditableObject()?.objectId??"none";var pointed=interaction?.GetCurrentPointedEditableObject()?.objectId??"none";live.text=$"session: {conditionManager?.sessionId??"none"} · {(conditionManager?.sessionStarted==true?"READY":"idle")}\ncondition: {conditionManager?.condition} | peer: {protocol?.CurrentPeerUuid??"none"}\nAPI: {(researcherControl?.IsReachable==true?"reachable":"unverified/error")} {researcherControl?.BaseUrl}\ntask: {quest?.GetCurrentTask()?.step.ToString()??"none"} · {quest?.GetCurrentObjectiveText()}\nselected: {selected} | pointed: {pointed}\nC3: {dynamicStory?.WaitingForNextTask}";}
        private void Note(string value){var item=DateTime.Now.ToString("HH:mm:ss")+"  "+value;lines.Enqueue(item);while(lines.Count>20)lines.Dequeue();if(log)log.text=string.Join("\n",lines);}
        private static void AddHeader(Transform parent,string text){var t=AddText(parent,text,13,FontStyles.Bold);t.color=new Color(.42f,.78f,1f);}
        private static TMP_Text AddText(Transform parent,string text,float size,FontStyles style){var go=new GameObject("Text",typeof(RectTransform),typeof(TextMeshProUGUI),typeof(LayoutElement));go.transform.SetParent(parent,false);var tmp=go.GetComponent<TextMeshProUGUI>();tmp.text=text;tmp.fontSize=size;tmp.fontStyle=style;tmp.color=Color.white;tmp.textWrappingMode=TextWrappingModes.Normal;go.GetComponent<LayoutElement>().preferredHeight=size>16?28:20;return tmp;}
        private static GameObject CreateBox(string name,Transform parent,Color color){var go=new GameObject(name,typeof(RectTransform),typeof(Image));go.transform.SetParent(parent,false);go.GetComponent<Image>().color=color;return go;}
        private static void AddButtons(Transform parent,(string,Action)[] specs){var row=new GameObject("ButtonRow",typeof(RectTransform),typeof(HorizontalLayoutGroup),typeof(LayoutElement));row.transform.SetParent(parent,false);row.GetComponent<HorizontalLayoutGroup>().spacing=4;row.GetComponent<LayoutElement>().preferredHeight=28;foreach(var spec in specs){var button=CreateBox(spec.Item1,row.transform,new Color(.12f,.22f,.34f,1)).AddComponent<Button>();button.targetGraphic=button.GetComponent<Image>();button.onClick.AddListener(()=>spec.Item2());var label=AddText(button.transform,spec.Item1,10,FontStyles.Bold);label.alignment=TextAlignmentOptions.Center;var r=label.rectTransform;r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=Vector2.zero;r.offsetMax=Vector2.zero;}}
    }
}
